### ISSUE TITLE
Yocto tauri L, icu-75 fails, scarthgap

### ISSUE THREAD

**Issue by ycardaillac** [phytec/meta-ampliphy#2] opened 2024-07-09 07:47 UTC
Step to reproduce :

1.  `repo init --repo-url=https://git.phytec.de/git/git-repo --repo-branch=stable -u git://git.phytec.de/phy2octo`
2.  choose 12: `12: imx8mm`
3.  choose 1: `1: BSP-Yocto-Ampliphy-i.MX8MM-master`
4.  choose 2: `2: phygate-tauri-l-imx8mm-2:`

That leads to a local.conf with:

```
MACHINE ?= "phygate-tauri-l-imx8mm-2"

DISTRO ?= "ampliphy-vanilla-master-u-boot-master"
```

I've added :
`ACCEPT_FSL_EULA = "1"`

I'm working on ubuntu 22.04.

Here the error when building phytec-headless-image:
```
ERROR: icu-75-1-r0 do_make_icudata: ExecutionError('/data/projects/yocto-phytec-scarthgap/build/tmp-ampliphy/work/cortexa53-crypto-phytec-linux/icu/75-1/temp/run.do_make_icudata.135475', 1, None, None)
ERROR: Logfile of failure stored in: /data/projects/yocto-phytec-scarthgap/build/tmp-ampliphy/work/cortexa53-crypto-phytec-linux/icu/75-1/temp/log.do_make_icudata.135475
Log data follows:
| DEBUG: Executing shell function do_make_icudata
| cp: cannot stat '/data/projects/yocto-phytec-scarthgap/build/tmp-ampliphy/work/cortexa53-crypto-phytec-linux/icu/75-1/data': No such file or directory
| WARNING: exit code 1 from a shell command.
ERROR: Task (/data/projects/yocto-phytec-scarthgap/sources/poky/../poky/meta/recipes-support/icu/icu_75-1.bb:do_make_icudata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1656 tasks of which 1634 didn't need to be rerun and 1 failed.
```

Log of failure : `build/tmp-ampliphy/work/cortexa53-crypto-phytec-linux/icu/75-1/temp/run.do_make_icudata.135475` :
```
DEBUG: Executing shell function do_make_icudata
cp: cannot stat '/data/projects/yocto-phytec-scarthgap/build/tmp-ampliphy/work/cortexa53-crypto-phytec-linux/icu/75-1/data': No such file or directory
WARNING: exit code 1 from a shell command.
```

**Comment by ymoog** [comment] 2024-07-09 08:05
This is an issue caused by upstream OpenEmbedded. We have sent a fix for this issue upstream. 
You can track the progress here: https://patchwork.yoctoproject.org/project/oe-core/patch/20240709062539.4581-1-s.mueller-klieser@phytec.de/

**Closed as completed** 2024-09-25 16:22 UTC
